%% Akshita Matlab Code Intro

X = readtable('cohort5year1920.txt');
%%

Xc = [X.Dropout_Count_,...
    X.GoldenStateSealMeritDiploma_Count_,...
    X.MetUC_CSUGradReq_s_Count_,...
    X.Non_GraduateCompleters_Count_,...
    X.Transfers_Count_,...
    X.Dropout_Count_];
    